package com.xu.walker.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xu.walker.db.bean.LoginInfo;
import com.xu.walker.db.bean.TrajectoryDBBean;

import com.xu.walker.db.LoginInfoDao;
import com.xu.walker.db.TrajectoryDBBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loginInfoDaoConfig;
    private final DaoConfig trajectoryDBBeanDaoConfig;

    private final LoginInfoDao loginInfoDao;
    private final TrajectoryDBBeanDao trajectoryDBBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loginInfoDaoConfig = daoConfigMap.get(LoginInfoDao.class).clone();
        loginInfoDaoConfig.initIdentityScope(type);

        trajectoryDBBeanDaoConfig = daoConfigMap.get(TrajectoryDBBeanDao.class).clone();
        trajectoryDBBeanDaoConfig.initIdentityScope(type);

        loginInfoDao = new LoginInfoDao(loginInfoDaoConfig, this);
        trajectoryDBBeanDao = new TrajectoryDBBeanDao(trajectoryDBBeanDaoConfig, this);

        registerDao(LoginInfo.class, loginInfoDao);
        registerDao(TrajectoryDBBean.class, trajectoryDBBeanDao);
    }
    
    public void clear() {
        loginInfoDaoConfig.clearIdentityScope();
        trajectoryDBBeanDaoConfig.clearIdentityScope();
    }

    public LoginInfoDao getLoginInfoDao() {
        return loginInfoDao;
    }

    public TrajectoryDBBeanDao getTrajectoryDBBeanDao() {
        return trajectoryDBBeanDao;
    }

}
